name: Test

on:
  push:
    branches: [ $default-branch ]
  pull_request:

env:
  NOKOGIRI_USE_SYSTEM_LIBRARIES: true
  SPEC_OPTS: '--backtrace'
  VIPS_HOME: /usr/local/vips

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Run Standard Ruby linter
        run: bundle exec standardrb --no-fix --fail-fast
        continue-on-error: true

  test:
    name: Functional Testing
    runs-on: ubuntu-20.04 # In order to install libvips 8.9+ version

    strategy:
      matrix:
        ruby-version:
#          - 2.1
#          - 2.2
#          - 2.3
#          - 2.4
#          - 2.5
#          - 2.6
          - 2.7
#          - jruby
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Updates apt
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo apt-get update -qq -o Acquire::Retries=3

      - name: Install libvips
        env:
          DEBIAN_FRONTEND: noninteractive
        run:
          sudo apt install --fix-missing -qq --no-install-recommends -o Acquire::Retries=3
            git build-essential automake libtool swig  libxml2-dev libfftw3-dev
            libmagickwand-dev libopenexr-dev liborc-0.4-0 gobject-introspection libgsf-1-dev
            libglib2.0-dev liborc-0.4-dev gtk-doc-tools libopenslide-dev libmatio-dev libgif-dev
            libwebp-dev libjpeg-turbo8-dev libexpat1-dev
            gettext
            libcfitsio-dev
            libexpat1-dev
            libfftw3-dev
            libgif-dev
            libglib2.0-dev
            libgsf-1-dev
            libjpeg-turbo8-dev
            liblcms2-dev
            libmagickwand-dev
            libmatio-dev
            libopenexr-dev
            libopenslide-dev
            liborc-0.4-dev
            libpango1.0-dev
            libpoppler-glib-dev
            libtiff5-dev
            libwebp-dev
            librsvg2-dev
            libmagick++-dev
      - name: Prepare ENV for libvips
        run:
          echo "${VIPS_HOME}/bin" >> $GITHUB_PATH

      - name: Build Custom Lib Vips
        run:
          bash ./install-vips.sh
        env:
          PATH: /usr/local/vips/bin:${{env.PATH}}
          LD_LIBRARY_PATH: /usr/local/vips/lib:${{env.LD_LIBRARY_PATH}}
          PKG_CONFIG_PATH: /usr/local/vips/lib/pkgconfig:${{env.PKG_CONFIG_PATH}}
          VIPS_VERSION_MAJOR: 8
          VIPS_VERSION_MINOR: 7
          VIPS_VERSION_MICRO: 2


      - name: Run Tests
        run: bundle exec rake spec
        env:
          PATH: /usr/local/vips/bin:${{env.PATH}}
          LD_LIBRARY_PATH: /usr/local/vips/lib:${{env.LD_LIBRARY_PATH}}
          PKG_CONFIG_PATH: /usr/local/vips/lib/pkgconfig:${{env.PKG_CONFIG_PATH}}
