name: Test

on:
  push:
    branches: [ $default-branch ]
  pull_request:

env:
  NOKOGIRI_USE_SYSTEM_LIBRARIES: true
  SPEC_OPTS: '--backtrace'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Run Standard Ruby linter
        run: bundle exec standardrb --no-fix --fail-fast
        continue-on-error: true

  test:
    name: Functional Testing
    runs-on: ubuntu-20.04 # In order to install libvips 8.9+ version

    strategy:
      matrix:
        ruby-version:
#          - 2.1
#          - 2.2
#          - 2.3
#          - 2.4
#          - 2.5
#          - 2.6
          - 2.7
#          - jruby
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Updates apt
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo apt-get update -qq -o Acquire::Retries=3

      - name: Install libvips
        env:
          DEBIAN_FRONTEND: noninteractive
        run:
          sudo apt install --fix-missing -qq -o Acquire::Retries=3
            libvips libvips-dev libvips-tools

      - name: Run Tests
        run: bundle exec rake spec
