name: Test

on:
  push:
    branches: [ $default-branch ]
  pull_request:

env:
  NOKOGIRI_USE_SYSTEM_LIBRARIES: true

jobs:
  test:
    name: Functional Testing
    runs-on: ubuntu-20.04 # In order to install libvips 8.9+ version

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 'truffleruby-20.3.0'
          bundler-cache: true

      - name: Install libvips
        env:
          DEBIAN_FRONTEND: noninteractive
        run:
          sudo apt install --fix-missing -qq --no-install-recommends
            libvips libvips-dev libvips-tools
            gettext
            libcfitsio-dev
            libexpat1-dev
            libfftw3-dev
            libgif-dev
            libglib2.0-dev
            libgsf-1-dev
            libjpeg-turbo8-dev
            liblcms2-dev
            libmagickwand-dev
            libmatio-dev
            libopenexr-dev
            libopenslide-dev
            liborc-0.4-dev
            libpango1.0-dev
            libpoppler-glib-dev
            libtiff5-dev
            libwebp-dev
            librsvg2-dev
            libmagick++-dev


      - name: Run Tests
        run: bundle exec rake spec
        env:
          SPEC_OPTS: '--backtrace'
